version: '3.8'
services:
  redis:
    image: redis
    ports:
      - "6379:6379"
  stock-api:
    build: .
    ports:
      - "3000:3000"
    environment:
      REDIS_URL: redis://redis:6379
      FMP_API_KEY: demo
    depends_on:
      - redis
